import Vue from 'vue'
import {
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Link,
  Checkbox,
  Header,
  Container,
  Main,
  Footer,
  Aside,
  Menu,
  Submenu,
  MenuItem,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Calendar,
  Dialog,
  Row,
  Col,
  Select,
  Option,
  Table,
  TableColumn,
  Pagination,
  MessageBox,
  Tree,
  Backtop,
  Drawer
} from 'element-ui'
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Link)
Vue.use(Checkbox)
Vue.use(Header)
Vue.use(Container)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Aside)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Calendar)
Vue.use(Dialog)
Vue.use(Row)
Vue.use(Col)
Vue.use(Select)
Vue.use(Option)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Tree)
Vue.use(Backtop)
Vue.use(Drawer)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
